# Generated by Django 3.1.4 on 2021-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userhabits_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='facebook',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='instagram',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='twitter',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='Test', max_length=25),
        ),
    ]
