# Generated by Django 3.1.4 on 2021-03-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210316_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabits',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
    ]
