# Generated by Django 3.1.4 on 2021-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210316_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='optional',
            name='background_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='optional',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
