# Generated by Django 3.1.4 on 2021-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210321_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='background_img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='optional',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
