# Generated by Django 3.1.4 on 2021-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210321_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='profile_img',
            field=models.ImageField(height_field=400, null=True, upload_to='gallery', width_field=400),
        ),
    ]
