# Generated by Django 3.1.4 on 2021-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210321_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
