# Generated by Django 3.1.4 on 2021-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210324_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='twitter',
            field=models.CharField(default='https://twitter.com/', max_length=100, null=True),
        ),
    ]
