# Generated by Django 3.1.4 on 2021-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210331_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optional',
            name='background_img',
            field=models.ImageField(blank=True, default='/default_background.jpeg', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='optional',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='facebook',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='instagram',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='optional',
            name='profile_img',
            field=models.ImageField(blank=True, default='/boris.webp', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='optional',
            name='twitter',
            field=models.CharField(blank=True, default='https://twitter.com/', max_length=100, null=True),
        ),
    ]
